### ISSUE TITLE
Year and month designations aren't supported

### ISSUE THREAD

**Issue by sugar700** [FauxFaux/time-parse#1]
For example, `P3Y6M4DT12H30M5S` represents a duration of "three years, six months, four days, twelve hours, thirty minutes, and five seconds".

**Comment by FauxFaux** [comment]
This was intentional, and was documented on the original issue, which I have now lost.

These are (very) poorly defined, and probably can't be implemented properly in a generic library like this.

Where have you seen them?

**Comment by sugar700** [comment]
I suppose that's fair. I was concerned about the library not accepting all of RFC 3339, but I think this may be fine, considering the ambiguity of what does "a month" mean.
